# Generated by Django 3.2.22 on 2024-02-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedd', '0001_initial'),
        ('features', '0002_auto_20240203_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='wedd.matrimonialprofile'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='wedd.matrimonialprofile'),
        ),
    ]
